/*
 * EXT_INTRUPT.h
 *
 *  Created on: Sep 3, 2022
 *      Author: AMR ELKOTT
 */

#ifndef MCAL_EXT_INTERRUPT_H_
#define MCAL_EXT_INTERRUPT_H_

#include "EXT_INTERRUPT_CFG.h"
#include "../REGISTERS_ADDRESSES.h"
#include "../../MACROS.h"

#define GLOBAL_INTERRUPT_ENABLE  1
#define GLOBAL_INTERRUPT_DISABLE 0

#define EXTERNAL_INTERRUPT_INT0 0
#define EXTERNAL_INTERRUPT_INT1 1
#define EXTERNAL_INTERRUPT_INT2 2

#define INTERRUPT_INT0_LOW_LEVEL      0
#define INTERRUPT_INT0_LOGICAL_CHANGE 1
#define INTERRUPT_INT0_RISING_EDGE    2
#define INTERRUPT_INT0_FALLING_EDGE   3

#define INTERRUPT_INT1_LOW_LEVEL      0
#define INTERRUPT_INT1_LOGICAL_CHANGE 1
#define INTERRUPT_INT1_RISING_EDGE    2
#define INTERRUPT_INT1_FALLING_EDGE   3

#define INTERRUPT_INT2_RISING_EDGE    0
#define INTERRUPT_INT2_FALLING_EDGE   1


void GLOBAL_INTERRUPT();
void EXTERNAL_INT0();
void EXTERNAL_INT1();
void EXTERNAL_INT2();



#endif /* MCAL_EXT_INTERRUPT_H_ */
