/*
 * EXT_INTERUPT_CFG.h
 *
 *  Created on: Sep 3, 2022
 *      Author: AMR ELKOTT
 */

#ifndef MCAL_EXT_INTERRUPT_CFG_H_
#define MCAL_EXT_INTERRUPT_CFG_H_



#define GLOBAL_INTERRUPT_STATUS GLOBAL_INTERRUPT_ENABLE


#define EXTERNAL_INTERRUPT_INT0_STATUS INTERRUPT_INT0_FALLING_EDGE
#define EXTERNAL_INTERRUPT_INT1_STATUS INTERRUPT_INT1_FALLING_EDGE
#define EXTERNAL_INTERRUPT_INT2_STATUS INTERRUPT_INT2_FALLING_EDGE



#endif /* MCAL_EXT_INTERRUPT_CFG_H_ */
