/*
 * ADC_CFG.h
 *
 *  Created on: Sep 23, 2022
 *      Author: AMR ELKOTT
 */

#ifndef MCAL_ADC_CFG_H_
#define MCAL_ADC_CFG_H_

#define ADC_VREF_SELECTED   ADC_VREF_AVCC

#define ADC_ADJUST_SELECTED ADC_RIGHT_ADJUST

#define ADC_CHANNEL_SELECTED ADC_CHANNEL1

#define ADC_MODE ADC_AUTO_TRIGGER

#define ADC_INTERRUPT ADC_INTERRUPT_DISABLE

#define ADC_PRESCALLER ADC_PRESCALLER128


#endif /* MCAL_ADC_CFG_H_ */
